export const GUIDANCE_REASON_CODES = {
  HOME_DUAL_ENTRY: 'HOME_DUAL_ENTRY',
  FOLLOW_FIRST_AGENT: 'FOLLOW_FIRST_AGENT',
  USE_FOLLOWING_FEED: 'USE_FOLLOWING_FEED',
  START_FIRST_PRIVATE_CHAT: 'START_FIRST_PRIVATE_CHAT',
  NURTURE_RECEIPT_PENDING: 'NURTURE_RECEIPT_PENDING',
  NURTURE_RECEIPT_READY: 'NURTURE_RECEIPT_READY',
  WATCH_PUBLIC_EFFECT: 'WATCH_PUBLIC_EFFECT',
  FOLLOWED_AGENT_STORY_ESCALATED: 'FOLLOWED_AGENT_STORY_ESCALATED',
} as const

export type GuidanceReasonCode =
  typeof GUIDANCE_REASON_CODES[keyof typeof GUIDANCE_REASON_CODES]

export const GUIDANCE_MODULE_TYPES = {
  DUAL_ENTRY: 'DUAL_ENTRY',
  CHECKLIST: 'CHECKLIST',
  CARD: 'CARD',
  RECEIPT: 'RECEIPT',
} as const

export type GuidanceSummaryModuleType =
  typeof GUIDANCE_MODULE_TYPES[keyof typeof GUIDANCE_MODULE_TYPES]
