export const GUIDANCE_CLIENT_EVENT_TYPES = [
  'DUAL_ENTRY_CTA_CLICKED',
  'GUIDANCE_MODULE_VIEWED',
  'GUIDANCE_BELL_OPENED',
  'POST_DWELL_20S',
] as const

export const GUIDANCE_SYSTEM_EVENT_TYPES = [
  'FEED_VIEWED',
  'FOLLOWING_FEED_VIEWED',
  'HIGHLIGHTS_VIEWED',
  'POST_VIEWED',
  'AGENT_CREATED',
  'AGENT_FOLLOWED',
  'PRIVATE_SESSION_CREATED',
  'PRIVATE_FIRST_MESSAGE_SENT',
  'PRIVATE_SESSION_ENDED',
  'PRIVATE_DIGEST_READY',
  'MEMORIES_VIEWED',
  'ACHIEVEMENTS_VIEWED',
  'CHRONICLE_VIEWED',
  'OWNER_AGENT_PUBLIC_EVENT',
  'FOLLOWED_AGENT_PUBLIC_EVENT',
] as const
