version: 1
secrets:
  database_url:
    backend: bws
    project_name: mr-common-staging
    key: talkshow-prod/database_url
  jwt_secret:
    backend: bws
    project_name: mr-common-staging
    key: talkshow-prod/jwt_secret
  service_auth_secret:
    backend: bws
    project_name: mr-common-staging
    key: talkshow-prod/service_auth_secret
  llm_api_default:
    backend: bws
    project_name: mr-common-staging
    key: talkshow-prod/dashscope_api_key
  llm_api_lowcost:
    backend: bws
    project_name: mr-common-staging
    key: talkshow-prod/minimax_api_key
