ALTER TABLE "human_users"
ADD COLUMN IF NOT EXISTS "birth_date" DATE;

ALTER TABLE "agents"
ALTER COLUMN "model" DROP DEFAULT;

ALTER TABLE "agents"
ALTER COLUMN "model" DROP NOT NULL;

ALTER TABLE "agent_search_docs"
ALTER COLUMN "model" DROP NOT NULL;
