apiVersion: v1
kind: ConfigMap
metadata:
  name: forum-app-config
  namespace: funforum
data:
  NODE_ENV: development
  NODE_OPTIONS: "--max-old-space-size=1536"
  CORS_ORIGINS: http://localhost:3000,http://localhost:3001
  MEDIA_LOCAL_DIR: /var/media-assets
  RUNTIME_LEADER_TTL_MS: "120000"
