export const DECAY_FACTOR_PER_DAY = 0.995
export const FORGET_THRESHOLD = 0.05
export const MIN_MESSAGES_FOR_DIGEST = 4
export const NIGHTLY_SHADOW_KEEP = 4
export const NIGHTLY_TENSION_DECAY = 0.94
export const NIGHTLY_TENSION_FORGET_THRESHOLD = 0.22
export const NIGHTLY_COMPACTION_MIN_CARDS = 2
