import { createBrowserRouter } from 'react-router'
import { Navigate } from 'react-router'
import { RouteErrorBoundary } from './RouteErrorBoundary'
import { AppShellContainer } from './shell/AppShellContainer'
import {
  AccountSettingsPage,
  AdminShellContainer,
  AdminGovernancePage,
  AdminMediaAssetsPage,
  AdminMediaPromptsPage,
  AdminProgrammingPage,
  AdminCueBoardPage,
  AdminAutoPatchInboxPage,
  AdminCueProjectionPreviewPage,
  AdminMediaPlanAuditPage,
  AdminUsersPage,
  AdminInvitesPage,
  AdminFeedbackPage,
  AdminHotTopicPage,
  AdminRuntimePage,
  AdminWarmupPage,
  AiContentHelpPage,
  ChatRoomListPage,
  ChatRoomPage,
  CommunitiesPage,
  CommunityFeedPage,
  CommunitySettingsPage,
  FeedPage,
  FeedbackPage,
  HelpCenterPage,
  HighlightsPage,
  StoryProgressPage,
  RecommendationPage,
  SearchPage,
  InboxPage,
  LoginPage,
  MyActivityPage,
  PostDetailPage,
  PrivacyPage,
  PrivateChatVerificationPage,
  ReportAppealDeletePage,
  RegisterPage,
  SafetyCenterPage,
  SuspenseWrap,
  TermsPage,
  HotTopicRulesPage,
} from './route-components'

export const router = createBrowserRouter([
  {
    path: '/login',
    element: <SuspenseWrap><LoginPage /></SuspenseWrap>,
    errorElement: <RouteErrorBoundary />,
  },
  {
    path: '/register',
    element: <SuspenseWrap><RegisterPage /></SuspenseWrap>,
    errorElement: <RouteErrorBoundary />,
  },
  {
    path: '/',
    element: <AppShellContainer />,
    errorElement: <RouteErrorBoundary />,
    children: [
      { index: true, element: <SuspenseWrap><FeedPage /></SuspenseWrap> },
      { path: 'feed', element: <SuspenseWrap><FeedPage /></SuspenseWrap> },
      { path: 'recommended', element: <SuspenseWrap><RecommendationPage /></SuspenseWrap> },
      { path: 'search', element: <SuspenseWrap><SearchPage /></SuspenseWrap> },
      { path: 'agents/manage', element: <SuspenseWrap><RecommendationPage /></SuspenseWrap> },
      { path: 'agents/:agentId', element: <SuspenseWrap><RecommendationPage /></SuspenseWrap> },
      { path: 'agents/:agentId/:tab', element: <SuspenseWrap><RecommendationPage /></SuspenseWrap> },
      { path: 'posts/:postId', element: <SuspenseWrap><PostDetailPage /></SuspenseWrap> },
      { path: 'c/:slug', element: <SuspenseWrap><CommunityFeedPage /></SuspenseWrap> },
      { path: 'c/:slug/settings', element: <SuspenseWrap><CommunitySettingsPage /></SuspenseWrap> },
      { path: 'highlights', element: <SuspenseWrap><HighlightsPage /></SuspenseWrap> },
      { path: 'story-progress', element: <SuspenseWrap><StoryProgressPage /></SuspenseWrap> },
      { path: 'help', element: <SuspenseWrap><HelpCenterPage /></SuspenseWrap> },
      { path: 'terms', element: <SuspenseWrap><TermsPage /></SuspenseWrap> },
      { path: 'privacy', element: <SuspenseWrap><PrivacyPage /></SuspenseWrap> },
      { path: 'help/ai-content', element: <SuspenseWrap><AiContentHelpPage /></SuspenseWrap> },
      { path: 'help/hot-topic-rules', element: <SuspenseWrap><HotTopicRulesPage /></SuspenseWrap> },
      { path: 'help/private-chat-verification', element: <SuspenseWrap><PrivateChatVerificationPage /></SuspenseWrap> },
      { path: 'help/report-appeal-delete', element: <SuspenseWrap><ReportAppealDeletePage /></SuspenseWrap> },
      { path: 'inbox', element: <SuspenseWrap><InboxPage /></SuspenseWrap> },
      { path: 'communities', element: <SuspenseWrap><CommunitiesPage /></SuspenseWrap> },
      { path: 'my/activity', element: <SuspenseWrap><MyActivityPage /></SuspenseWrap> },
      { path: 'settings/account', element: <SuspenseWrap><AccountSettingsPage /></SuspenseWrap> },
      { path: 'feedback', element: <SuspenseWrap><FeedbackPage /></SuspenseWrap> },
      { path: 'safety', element: <SuspenseWrap><SafetyCenterPage /></SuspenseWrap> },
      { path: 'rooms', element: <SuspenseWrap><ChatRoomListPage /></SuspenseWrap> },
      { path: 'rooms/:roomId', element: <SuspenseWrap><ChatRoomPage /></SuspenseWrap> },
    ],
  },
  {
    path: '/admin',
    element: <AdminShellContainer />,
    errorElement: <RouteErrorBoundary />,
    children: [
      { index: true, element: <Navigate to="governance" replace /> },
      { path: 'governance', element: <SuspenseWrap><AdminGovernancePage /></SuspenseWrap> },
      { path: 'programming', element: <SuspenseWrap><AdminProgrammingPage /></SuspenseWrap> },
      { path: 'cue-board', element: <SuspenseWrap><AdminCueBoardPage /></SuspenseWrap> },
      { path: 'auto-patches', element: <SuspenseWrap><AdminAutoPatchInboxPage /></SuspenseWrap> },
      { path: 'cue-projection', element: <SuspenseWrap><AdminCueProjectionPreviewPage /></SuspenseWrap> },
      { path: 'media-plan-audit', element: <SuspenseWrap><AdminMediaPlanAuditPage /></SuspenseWrap> },
      { path: 'media-prompts', element: <SuspenseWrap><AdminMediaPromptsPage /></SuspenseWrap> },
      { path: 'media-assets', element: <SuspenseWrap><AdminMediaAssetsPage /></SuspenseWrap> },
      { path: 'admins', element: <SuspenseWrap><AdminUsersPage /></SuspenseWrap> },
      { path: 'invites', element: <SuspenseWrap><AdminInvitesPage /></SuspenseWrap> },
      { path: 'feedback', element: <SuspenseWrap><AdminFeedbackPage /></SuspenseWrap> },
      { path: 'hot-topic', element: <SuspenseWrap><AdminHotTopicPage /></SuspenseWrap> },
      { path: 'runtime', element: <SuspenseWrap><AdminRuntimePage /></SuspenseWrap> },
      { path: 'warmup', element: <SuspenseWrap><AdminWarmupPage /></SuspenseWrap> },
    ],
  },
])
