import { createBrowserRouter } from 'react-router'
import { AppShellContainer } from './shell/AppShellContainer'
import {
  AccountSettingsPage,
  AdminPanel,
  AiContentHelpPage,
  ChatRoomListPage,
  ChatRoomPage,
  CommunitiesPage,
  CommunityFeedPage,
  FeedPage,
  FeedbackPage,
  HelpCenterPage,
  HighlightsPage,
  SearchPage,
  InboxPage,
  LoginPage,
  MyActivityPage,
  PostDetailPage,
  PrivacyPage,
  PrivateChatVerificationPage,
  ReportAppealDeletePage,
  RegisterPage,
  SafetyCenterPage,
  SuspenseWrap,
  TermsPage,
  HotTopicRulesPage,
} from './route-components'

export const router = createBrowserRouter([
  {
    path: '/login',
    element: <SuspenseWrap><LoginPage /></SuspenseWrap>,
  },
  {
    path: '/register',
    element: <SuspenseWrap><RegisterPage /></SuspenseWrap>,
  },
  {
    path: '/',
    element: <AppShellContainer />,
    children: [
      { index: true, element: <SuspenseWrap><FeedPage /></SuspenseWrap> },
      { path: 'search', element: <SuspenseWrap><SearchPage /></SuspenseWrap> },
      { path: 'posts/:postId', element: <SuspenseWrap><PostDetailPage /></SuspenseWrap> },
      { path: 'c/:slug', element: <SuspenseWrap><CommunityFeedPage /></SuspenseWrap> },
      { path: 'highlights', element: <SuspenseWrap><HighlightsPage /></SuspenseWrap> },
      { path: 'help', element: <SuspenseWrap><HelpCenterPage /></SuspenseWrap> },
      { path: 'terms', element: <SuspenseWrap><TermsPage /></SuspenseWrap> },
      { path: 'privacy', element: <SuspenseWrap><PrivacyPage /></SuspenseWrap> },
      { path: 'help/ai-content', element: <SuspenseWrap><AiContentHelpPage /></SuspenseWrap> },
      { path: 'help/hot-topic-rules', element: <SuspenseWrap><HotTopicRulesPage /></SuspenseWrap> },
      { path: 'help/private-chat-verification', element: <SuspenseWrap><PrivateChatVerificationPage /></SuspenseWrap> },
      { path: 'help/report-appeal-delete', element: <SuspenseWrap><ReportAppealDeletePage /></SuspenseWrap> },
      { path: 'inbox', element: <SuspenseWrap><InboxPage /></SuspenseWrap> },
      { path: 'communities', element: <SuspenseWrap><CommunitiesPage /></SuspenseWrap> },
      { path: 'my/activity', element: <SuspenseWrap><MyActivityPage /></SuspenseWrap> },
      { path: 'settings/account', element: <SuspenseWrap><AccountSettingsPage /></SuspenseWrap> },
      { path: 'feedback', element: <SuspenseWrap><FeedbackPage /></SuspenseWrap> },
      { path: 'safety', element: <SuspenseWrap><SafetyCenterPage /></SuspenseWrap> },
      { path: 'rooms', element: <SuspenseWrap><ChatRoomListPage /></SuspenseWrap> },
      { path: 'rooms/:roomId', element: <SuspenseWrap><ChatRoomPage /></SuspenseWrap> },
      { path: 'admin', element: <SuspenseWrap><AdminPanel /></SuspenseWrap> },
    ],
  },
])
