/* GENERATED FILE. DO NOT EDIT BY HAND.
 * Source: ui/tokens/base.json + ui/tokens/themes/*.json
 * Generated by: scripts/ui/build-web-theme.mjs
 */

export const BASE_TOKENS = {
  "meta": {
    "token_version": "1.1.0",
    "name": "base",
    "description": "Base UI tokens aligned with morethan brand kit v1.1. Theme files may override subsets, primarily color.*.",
    "brand_source": "morethan_brandkit_v2/tokens/morethan.design-tokens.json"
  },
  "color": {
    "bg": "#ffffff",
    "surface": "#ffffff",
    "surface_elevated": "#f9fafb",
    "text_primary": "#111827",
    "text_secondary": "#4B5563",
    "text_muted": "#6b7280",
    "border": "#E5E7EB",
    "border_subtle": "#f3f4f6",
    "primary": "#283E68",
    "primary_hover": "#1e3058",
    "primary_active": "#162448",
    "on_primary": "#ffffff",
    "accent": "#E1703C",
    "accent_hover": "#cc5f30",
    "accent_active": "#b85227",
    "on_accent": "#ffffff",
    "danger": "#dc2626",
    "on_danger": "#ffffff",
    "success": "#16a34a",
    "on_success": "#ffffff",
    "warning": "#d97706",
    "on_warning": "#111827",
    "selection": "#e6ebf3",
    "agent_panel_selection_surface": "#e7edf7",
    "agent_panel_selection_text": "#233a63",
    "agent_panel_action_text": "#243B6B",
    "agent_panel_action_text_hover": "#1d3057",
    "agent_panel_stat_cool": "#48668f",
    "agent_panel_stat_cool_strong": "#2b569d",
    "agent_panel_stat_cool_tint": "rgba(72, 102, 143, 0.08)",
    "agent_panel_stat_warm": "#a36540",
    "agent_panel_stat_warm_strong": "#d07a3c",
    "agent_panel_stat_warm_tint": "rgba(163, 101, 64, 0.08)",
    "agent_panel_stat_track_cool": "rgba(54, 90, 140, 0.94)",
    "agent_panel_stat_track_mid": "rgba(215, 221, 230, 0.92)",
    "agent_panel_stat_track_warm": "rgba(184, 109, 58, 0.94)",
    "agent_panel_stat_track_solid": "rgba(54, 90, 140, 0.90)",
    "focus_ring": "#283E6866",
    "overlay": "#000000",
    "on_overlay": "#ffffff",
    "sentiment_negative": "#BC8F8F",
    "sentiment_positive": "#70A985"
  },
  "typography": {
    "font_family": {
      "sans": "Inter, Manrope, 'SF Pro Display', system-ui, -apple-system, sans-serif",
      "sans_cn": "'HarmonyOS Sans SC', 'Source Han Sans SC', 'Noto Sans CJK SC', system-ui, sans-serif",
      "mono": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
    },
    "size": {
      "caption": "12px",
      "body": "14px",
      "body_lg": "16px",
      "h3": "16px",
      "h2": "20px",
      "h1": "24px"
    },
    "line_height": {
      "caption": "16px",
      "body": "20px",
      "heading": "28px"
    },
    "weight": {
      "regular": 400,
      "medium": 500,
      "semibold": 600,
      "bold": 700
    }
  },
  "space": {
    "0": "0px",
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "24px",
    "6": "32px",
    "7": "40px",
    "8": "48px"
  },
  "radius": {
    "sm": "6px",
    "md": "8px",
    "lg": "16px",
    "full": "999px"
  },
  "shadow": {
    "none": "none",
    "sm": "0 1px 2px #0000000D",
    "md": "0 6px 16px #00000014"
  },
  "border": {
    "width": {
      "sm": "1px"
    }
  },
  "sizing": {
    "modal": {
      "sm": "420px",
      "md": "560px",
      "lg": "720px"
    },
    "textarea": {
      "min_height": "120px"
    }
  },
  "motion": {
    "duration_fast": "120ms",
    "duration_normal": "180ms",
    "ease_standard": "cubic-bezier(0.2, 0, 0, 1)"
  },
  "z": {
    "dropdown": 1000,
    "modal": 1100,
    "toast": 1200
  }
} as const

export const THEMES = {
  "default.dark": {
    "meta": {
      "theme": "default.dark",
      "extends": "base",
      "description": "morethan dark theme. Lighter navy primary, orange accent on dark ink."
    },
    "color": {
      "bg": "#0c1321",
      "surface": "#111b2e",
      "surface_elevated": "#16243d",
      "text_primary": "#e5e7eb",
      "text_secondary": "#cbd5e1",
      "text_muted": "#94a3b8",
      "border": "#24344f",
      "border_subtle": "#1b2a44",
      "primary": "#5a7ab5",
      "primary_hover": "#7994c7",
      "primary_active": "#3e5f9a",
      "on_primary": "#0c1321",
      "accent": "#E1703C",
      "accent_hover": "#f0855a",
      "accent_active": "#cc5f30",
      "on_accent": "#0c1321",
      "danger": "#dc2626",
      "on_danger": "#ffffff",
      "success": "#16a34a",
      "on_success": "#ffffff",
      "warning": "#d97706",
      "on_warning": "#111827",
      "selection": "#24344f",
      "agent_panel_selection_surface": "#e7edf7",
      "agent_panel_selection_text": "#233a63",
      "agent_panel_action_text": "#243B6B",
      "agent_panel_action_text_hover": "#1d3057",
      "agent_panel_stat_cool": "#48668f",
      "agent_panel_stat_cool_strong": "#2b569d",
      "agent_panel_stat_cool_tint": "rgba(72, 102, 143, 0.08)",
      "agent_panel_stat_warm": "#a36540",
      "agent_panel_stat_warm_strong": "#d07a3c",
      "agent_panel_stat_warm_tint": "rgba(163, 101, 64, 0.08)",
      "agent_panel_stat_track_cool": "rgba(54, 90, 140, 0.94)",
      "agent_panel_stat_track_mid": "rgba(215, 221, 230, 0.92)",
      "agent_panel_stat_track_warm": "rgba(184, 109, 58, 0.94)",
      "agent_panel_stat_track_solid": "rgba(54, 90, 140, 0.90)",
      "focus_ring": "#5a7ab580",
      "overlay": "#000000",
      "on_overlay": "#ffffff",
      "sentiment_negative": "#BC8F8F",
      "sentiment_positive": "#70A985"
    },
    "typography": {
      "font_family": {
        "sans": "Inter, Manrope, 'SF Pro Display', system-ui, -apple-system, sans-serif",
        "sans_cn": "'HarmonyOS Sans SC', 'Source Han Sans SC', 'Noto Sans CJK SC', system-ui, sans-serif",
        "mono": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
      },
      "size": {
        "caption": "12px",
        "body": "14px",
        "body_lg": "16px",
        "h3": "16px",
        "h2": "20px",
        "h1": "24px"
      },
      "line_height": {
        "caption": "16px",
        "body": "20px",
        "heading": "28px"
      },
      "weight": {
        "regular": 400,
        "medium": 500,
        "semibold": 600,
        "bold": 700
      }
    },
    "space": {
      "0": "0px",
      "1": "4px",
      "2": "8px",
      "3": "12px",
      "4": "16px",
      "5": "24px",
      "6": "32px",
      "7": "40px",
      "8": "48px"
    },
    "radius": {
      "sm": "6px",
      "md": "8px",
      "lg": "16px",
      "full": "999px"
    },
    "shadow": {
      "none": "none",
      "sm": "0 1px 2px #0000000D",
      "md": "0 6px 16px #00000014"
    },
    "border": {
      "width": {
        "sm": "1px"
      }
    },
    "sizing": {
      "modal": {
        "sm": "420px",
        "md": "560px",
        "lg": "720px"
      },
      "textarea": {
        "min_height": "120px"
      }
    },
    "motion": {
      "duration_fast": "120ms",
      "duration_normal": "180ms",
      "ease_standard": "cubic-bezier(0.2, 0, 0, 1)"
    },
    "z": {
      "dropdown": 1000,
      "modal": 1100,
      "toast": 1200
    }
  },
  "default.light": {
    "meta": {
      "theme": "default.light",
      "extends": "base",
      "description": "morethan light theme. Navy primary, orange accent on white."
    },
    "color": {
      "bg": "#ffffff",
      "surface": "#ffffff",
      "surface_elevated": "#f8f9fb",
      "text_primary": "#111827",
      "text_secondary": "#4B5563",
      "text_muted": "#6b7280",
      "border": "#E5E7EB",
      "border_subtle": "#f3f4f6",
      "primary": "#283E68",
      "primary_hover": "#1e3058",
      "primary_active": "#162448",
      "on_primary": "#ffffff",
      "accent": "#E1703C",
      "accent_hover": "#cc5f30",
      "accent_active": "#b85227",
      "on_accent": "#ffffff",
      "danger": "#dc2626",
      "on_danger": "#ffffff",
      "success": "#16a34a",
      "on_success": "#ffffff",
      "warning": "#d97706",
      "on_warning": "#111827",
      "selection": "#e6ebf3",
      "agent_panel_selection_surface": "#e7edf7",
      "agent_panel_selection_text": "#233a63",
      "agent_panel_action_text": "#243B6B",
      "agent_panel_action_text_hover": "#1d3057",
      "agent_panel_stat_cool": "#48668f",
      "agent_panel_stat_cool_strong": "#2b569d",
      "agent_panel_stat_cool_tint": "rgba(72, 102, 143, 0.08)",
      "agent_panel_stat_warm": "#a36540",
      "agent_panel_stat_warm_strong": "#d07a3c",
      "agent_panel_stat_warm_tint": "rgba(163, 101, 64, 0.08)",
      "agent_panel_stat_track_cool": "rgba(54, 90, 140, 0.94)",
      "agent_panel_stat_track_mid": "rgba(215, 221, 230, 0.92)",
      "agent_panel_stat_track_warm": "rgba(184, 109, 58, 0.94)",
      "agent_panel_stat_track_solid": "rgba(54, 90, 140, 0.90)",
      "focus_ring": "#283E6866",
      "overlay": "#000000",
      "on_overlay": "#ffffff",
      "sentiment_negative": "#BC8F8F",
      "sentiment_positive": "#70A985"
    },
    "typography": {
      "font_family": {
        "sans": "Inter, Manrope, 'SF Pro Display', system-ui, -apple-system, sans-serif",
        "sans_cn": "'HarmonyOS Sans SC', 'Source Han Sans SC', 'Noto Sans CJK SC', system-ui, sans-serif",
        "mono": "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
      },
      "size": {
        "caption": "12px",
        "body": "14px",
        "body_lg": "16px",
        "h3": "16px",
        "h2": "20px",
        "h1": "24px"
      },
      "line_height": {
        "caption": "16px",
        "body": "20px",
        "heading": "28px"
      },
      "weight": {
        "regular": 400,
        "medium": 500,
        "semibold": 600,
        "bold": 700
      }
    },
    "space": {
      "0": "0px",
      "1": "4px",
      "2": "8px",
      "3": "12px",
      "4": "16px",
      "5": "24px",
      "6": "32px",
      "7": "40px",
      "8": "48px"
    },
    "radius": {
      "sm": "6px",
      "md": "8px",
      "lg": "16px",
      "full": "999px"
    },
    "shadow": {
      "none": "none",
      "sm": "0 1px 2px #0000000D",
      "md": "0 6px 16px #00000014"
    },
    "border": {
      "width": {
        "sm": "1px"
      }
    },
    "sizing": {
      "modal": {
        "sm": "420px",
        "md": "560px",
        "lg": "720px"
      },
      "textarea": {
        "min_height": "120px"
      }
    },
    "motion": {
      "duration_fast": "120ms",
      "duration_normal": "180ms",
      "ease_standard": "cubic-bezier(0.2, 0, 0, 1)"
    },
    "z": {
      "dropdown": 1000,
      "modal": 1100,
      "toast": 1200
    }
  }
} as const

export type ThemeName = keyof typeof THEMES

export function applyTheme(theme: ThemeName) {
  document.documentElement.dataset.theme = theme
}

export function getTheme(): ThemeName {
  return (document.documentElement.dataset.theme as ThemeName) || 'default.light'
}
