const env = process.env

export const config = {
  port: parseInt(env.PORT || '4000', 10),
  nodeEnv: env.NODE_ENV || 'development',
  cors: {
    origins: env.CORS_ORIGINS?.split(',') || ['http://localhost:3000'],
  },
  db: {
    url: env.DATABASE_URL || `postgresql://${env.USER ?? 'postgres'}@localhost:5432/llm_forum_dev`,
    usePrisma: env.DB_PERSISTENCE === 'true',
  },
  auth: {
    jwtSecret: env.JWT_SECRET || 'dev-jwt-secret-change-in-production',
    jwtExpiresIn: env.JWT_EXPIRES_IN || '7d',
  },
  serviceAuth: {
    secret: env.SERVICE_AUTH_SECRET || 'dev-service-secret-change-in-production',
    timestampToleranceMs: 5 * 60 * 1000,
  },
  llm: {
    provider: env.LLM_PROVIDER || 'openai-compatible',
    model: env.LLM_MODEL || 'qwen-plus',
    apiKey: env.LLM_API_KEY || '',
    baseUrl: env.LLM_BASE_URL || 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    maxTokens: parseInt(env.LLM_MAX_TOKENS || '512', 10),
    temperature: parseFloat(env.LLM_TEMPERATURE || '0.8'),
    maxRetries: parseInt(env.LLM_MAX_RETRIES || '2', 10),
    timeoutMs: parseInt(env.LLM_TIMEOUT_MS || '30000', 10),
  },
  runtime: {
    enabled: env.RUNTIME_ENABLED === 'true',
    intervalMs: parseInt(env.RUNTIME_INTERVAL_MS || '5000', 10),
    batchSize: parseInt(env.RUNTIME_BATCH_SIZE || '10', 10),
    postIntervalMs: parseInt(env.RUNTIME_POST_INTERVAL_MS || '120000', 10),
    postMaxPerDay: parseInt(env.RUNTIME_POST_MAX_PER_DAY || '50', 10),
    queueBackend: env.RUNTIME_QUEUE_BACKEND === 'redis' ? 'redis' : 'in-memory',
    leaderBackend: env.RUNTIME_LEADER_BACKEND === 'redis' ? 'redis' : 'in-memory',
    redisUrl: env.RUNTIME_REDIS_URL || env.REDIS_URL || '',
    redisPrefix: env.RUNTIME_REDIS_PREFIX || 'llm-forum:runtime',
    redisConnectTimeoutMs: parseInt(env.RUNTIME_REDIS_CONNECT_TIMEOUT_MS || '5000', 10),
    queueVisibilityTimeoutMs: parseInt(env.RUNTIME_QUEUE_VISIBILITY_TIMEOUT_MS || '60000', 10),
    queueMaxRetries: parseInt(env.RUNTIME_QUEUE_MAX_RETRIES || '3', 10),
    queuePollTimeoutMs: parseInt(env.RUNTIME_QUEUE_POLL_TIMEOUT_MS || '100', 10),
    leaderTtlMs: parseInt(env.RUNTIME_LEADER_TTL_MS || '15000', 10),
  },
  sse: {
    broadcastBackend: env.SSE_BROADCAST_BACKEND === 'redis' ? 'redis' : 'local',
    redisUrl: env.SSE_REDIS_URL || env.RUNTIME_REDIS_URL || env.REDIS_URL || '',
    redisChannel: env.SSE_REDIS_CHANNEL || 'llm-forum:sse:broadcast',
    redisConnectTimeoutMs: parseInt(env.SSE_REDIS_CONNECT_TIMEOUT_MS || '5000', 10),
  },
  features: {
    layerStackV2: env.FF_LAYER_STACK_V2 === 'true',
    nurturePipelineV2: env.FF_NURTURE_PIPELINE_V2 === 'true',
    publicObservationMemory: env.FF_PUBLIC_OBSERVATION_MEMORY === 'true',
    socialGraphV1: env.FF_SOCIAL_GRAPH_V1 === 'true',
    socialGraphEffective: env.FF_SOCIAL_GRAPH_EFFECTIVE === 'true',
    socialGraphExplainer: env.FF_SOCIAL_GRAPH_EXPLAINER === 'true',
    agentStatsV1: env.FF_AGENT_STATS_V1 === 'true',
    agentStatsBehavior: env.FF_AGENT_STATS_BEHAVIOR === 'true',
    agentStatsRelationPolicy: env.FF_AGENT_STATS_RELATION_POLICY === 'true',
    agentStatsVotePolicy: env.FF_AGENT_STATS_VOTE_POLICY === 'true',
    agentStatsUi: env.FF_AGENT_STATS_UI === 'true',
  },
} as const
