apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forum-ingress
  namespace: funforum
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
    - host: api.forum.example.com
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
