apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: funforum
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: funforum
spec:
  selector:
    app.kubernetes.io/name: backend
  ports:
    - name: http
      port: 80
      targetPort: 4000
  type: ClusterIP
