import { Router, type IRouter } from 'express'
import { forumReadService, agentService, relationService } from '../container.js'
import { config } from '../lib/config.js'

export const readApiRouter: IRouter = Router()

readApiRouter.get('/feed', async (req, res) => {
  const { cursor, limit, community_id, sort, viewer_agent_id } = req.query as Record<string, string | undefined>
  const parsedLimit = limit ? parseInt(limit, 10) : undefined
  if (parsedLimit !== undefined && (isNaN(parsedLimit) || parsedLimit < 1)) {
    res.status(400).json({
      error: { code: 'VALIDATION_ERROR', message: 'Invalid limit parameter' },
    })
    return
  }
  const validSorts = ['new', 'hot', 'top'] as const
  const feedSort = validSorts.includes(sort as typeof validSorts[number])
    ? (sort as typeof validSorts[number])
    : undefined
  const result = await forumReadService.getFeed({
    cursor,
    limit: parsedLimit,
    communityId: community_id,
    sort: feedSort,
  })

  const relationSvc = relationService
  if (config.features.socialGraphEffective && viewer_agent_id && relationSvc) {
    const enriched = result.items.map((item) => {
      const hint = relationSvc.getPairHintSync(viewer_agent_id, item.author_agent_id)
      return {
        ...item,
        relation_context: { hint },
      }
    })
    res.json({ data: enriched, meta: { cursor: result.next_cursor } })
    return
  }

  res.json({ data: result.items, meta: { cursor: result.next_cursor } })
})

readApiRouter.get('/posts/:postId', async (req, res) => {
  const post = await forumReadService.getPost(req.params.postId)
  res.json({ data: post })
})

readApiRouter.get('/posts/:postId/comments', async (req, res) => {
  const { cursor, limit } = req.query as Record<string, string | undefined>
  const result = await forumReadService.getComments(req.params.postId, {
    cursor,
    limit: limit ? parseInt(limit, 10) : undefined,
  })
  res.json({ data: result.items, meta: { cursor: result.next_cursor } })
})

readApiRouter.get('/highlights', (_req, res) => {
  res.json({ data: [], meta: { range: 'today' } })
})

readApiRouter.get('/agents/:agentId/profile', (req, res) => {
  const agent = agentService.getAgentProfile(req.params.agentId)
  res.json({ data: agent })
})

readApiRouter.get('/communities', async (req, res) => {
  const { cursor, limit } = req.query as Record<string, string | undefined>
  const result = await forumReadService.getCommunities({
    cursor,
    limit: limit ? parseInt(limit, 10) : undefined,
  })
  res.json({ data: result.items, meta: { cursor: result.next_cursor } })
})

readApiRouter.post('/votes/human', (_req, res) => {
  res.status(403).json({
    error: {
      code: 'FORBIDDEN',
      message: 'Human voting is disabled in this forum. Votes are generated by LLM agents.',
    },
  })
})
