import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import { randomUUID } from 'node:crypto'
import { resolve } from 'node:path'
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml'
import type {
  KickoffAuthoringPatch,
  KickoffDataMode,
  KickoffImportReport,
  KickoffImportRunType,
  KickoffRunArtifacts,
  KickoffRunDetail,
  KickoffRunSummary,
  KickoffRuntimeReadiness,
} from '../../shared/kickoff-workflow.js'

const RUNS_ROOT = resolve(process.cwd(), '.ai/.tmp/kickoff-runs')
const LATEST_RUN_PATH = resolve(RUNS_ROOT, 'latest-run.json')
const DATA_MODE_PATH = resolve(RUNS_ROOT, 'current-mode.json')

async function safeReadJson<T>(path: string): Promise<T | null> {
  try {
    return JSON.parse(await readFile(path, 'utf8')) as T
  } catch {
    return null
  }
}

async function safeReadText(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf8')
  } catch {
    return null
  }
}

export class KickoffRunArtifactService {
  async createRun(input: {
    run_type: KickoffImportRunType
    mode: KickoffRunSummary['mode']
    profile_id: KickoffRunSummary['profile_id']
    patch_id?: string | null
    suite_id?: string | null
    suite_label?: string | null
    kickoff_batch_id?: string | null
    warmup_batch_id?: string | null
    baseline_id?: string | null
  }): Promise<KickoffRunSummary> {
    await mkdir(RUNS_ROOT, { recursive: true })
    const runId = `${new Date().toISOString().replace(/[:.]/g, '-')}-${randomUUID().slice(0, 8)}`
    const artifactDir = resolve(RUNS_ROOT, runId)
    await mkdir(artifactDir, { recursive: true })

    const summary: KickoffRunSummary = {
      run_id: runId,
      run_type: input.run_type,
      mode: input.mode ?? null,
      profile_id: input.profile_id ?? null,
      patch_id: input.patch_id ?? null,
      suite_id: input.suite_id ?? null,
      suite_label: input.suite_label ?? null,
      kickoff_batch_id: input.kickoff_batch_id ?? null,
      warmup_batch_id: input.warmup_batch_id ?? null,
      baseline_id: input.baseline_id ?? null,
      failed_phase: null,
      artifact_dir: artifactDir,
      started_at: new Date().toISOString(),
      completed_at: null,
    }
    await this.writeJson(resolve(artifactDir, 'run-summary.json'), summary)
    await this.writeJson(LATEST_RUN_PATH, { run_id: runId })
    return summary
  }

  async writeContextPack(runId: string, payload: Record<string, unknown>): Promise<string> {
    const path = this.contextPackPath(runId)
    await this.writeJson(path, payload)
    return path
  }

  async writePatch(runId: string, patch: KickoffAuthoringPatch): Promise<string> {
    const path = this.generatedPatchPath(runId)
    await mkdir(resolve(path, '..'), { recursive: true })
    await writeFile(path, stringifyYaml(patch), 'utf8')
    return path
  }

  async writeImportReport(runId: string, report: KickoffImportReport): Promise<string> {
    const path = this.importReportPath(runId)
    await this.writeJson(path, report)
    return path
  }

  async writeReadiness(runId: string, readiness: KickoffRuntimeReadiness): Promise<string> {
    const path = this.readinessPath(runId)
    await this.writeJson(path, readiness)
    return path
  }

  async writeDiffSummary(runId: string, content: string): Promise<string> {
    const path = this.diffSummaryPath(runId)
    await mkdir(resolve(path, '..'), { recursive: true })
    await writeFile(path, content, 'utf8')
    return path
  }

  async writeRepairPatch(runId: string, patch: KickoffAuthoringPatch): Promise<string> {
    const repairPatch: KickoffAuthoringPatch = {
      ...patch,
      patch_meta: {
        ...patch.patch_meta,
        patch_id: `${patch.patch_meta.patch_id}-repair`,
        iteration: patch.patch_meta.iteration + 1,
        parent_patch_id: patch.patch_meta.patch_id,
        repair_of_patch_id: patch.patch_meta.patch_id,
      },
      operations: [],
      notes: [...(patch.notes ?? []), 'repair patch scaffold generated by kickoff importer'],
    }
    const path = this.repairPatchPath(runId)
    await mkdir(resolve(path, '..'), { recursive: true })
    await writeFile(path, stringifyYaml(repairPatch), 'utf8')
    return path
  }

  async writeFailureLog(runId: string, payload: Record<string, unknown>): Promise<string> {
    const path = this.failureLogPath(runId)
    await this.writeJson(path, payload)
    return path
  }

  async completeRun(runId: string, input: {
    failed_phase?: string | null
    suite_id?: string | null
    suite_label?: string | null
    kickoff_batch_id?: string | null
    warmup_batch_id?: string | null
    baseline_id?: string | null
  }): Promise<KickoffRunSummary> {
    const summaryPath = resolve(RUNS_ROOT, runId, 'run-summary.json')
    const current = (await safeReadJson<KickoffRunSummary>(summaryPath))!
    const next: KickoffRunSummary = {
      ...current,
      suite_id: input.suite_id ?? current.suite_id,
      suite_label: input.suite_label ?? current.suite_label,
      kickoff_batch_id: input.kickoff_batch_id ?? current.kickoff_batch_id,
      warmup_batch_id: input.warmup_batch_id ?? current.warmup_batch_id,
      baseline_id: input.baseline_id ?? current.baseline_id,
      failed_phase: input.failed_phase ?? null,
      completed_at: new Date().toISOString(),
    }
    await this.writeJson(summaryPath, next)
    await this.writeJson(LATEST_RUN_PATH, { run_id: runId })
    return next
  }

  async listRecentRuns(limit = 10): Promise<KickoffRunSummary[]> {
    let entries: string[]
    try {
      entries = await readdir(RUNS_ROOT)
    } catch {
      return []
    }
    const candidates = entries.filter((e) => !e.endsWith('.json'))
    candidates.sort().reverse()

    const summaries: KickoffRunSummary[] = []
    for (const dir of candidates.slice(0, limit)) {
      const summary = await safeReadJson<KickoffRunSummary>(
        resolve(RUNS_ROOT, dir, 'run-summary.json'),
      )
      if (summary) summaries.push(summary)
    }
    return summaries
  }

  async readLatestRun(): Promise<KickoffRunDetail | null> {
    const latest = await safeReadJson<{ run_id: string }>(LATEST_RUN_PATH)
    if (!latest?.run_id) return null
    return this.readRun(latest.run_id)
  }

  async readRun(runId: string): Promise<KickoffRunDetail | null> {
    const summary = await safeReadJson<KickoffRunSummary>(resolve(RUNS_ROOT, runId, 'run-summary.json'))
    if (!summary) return null
    const artifacts = this.buildArtifacts(runId)
    const patchText = await safeReadText(artifacts.generated_patch_path!)
    return {
      summary,
      artifacts,
      context_pack: await safeReadJson<Record<string, unknown>>(artifacts.context_pack_path!),
      patch: patchText ? (parseYaml(patchText) as KickoffAuthoringPatch) : null,
      import_report: await safeReadJson<KickoffImportReport>(artifacts.import_report_path!),
      readiness: await safeReadJson<KickoffRuntimeReadiness>(artifacts.readiness_snapshot_path!),
      diff_summary: await safeReadText(artifacts.diff_summary_path!),
      failure_log: await safeReadJson<Record<string, unknown>>(artifacts.failure_log_path!),
    }
  }

  async recordDataMode(input: {
    mode: KickoffDataMode
    profile?: string | null
    suite_id?: string | null
    suite_label?: string | null
    baseline_id?: string | null
  }): Promise<void> {
    await mkdir(RUNS_ROOT, { recursive: true })
    await this.writeJson(DATA_MODE_PATH, {
      ...input,
      recorded_at: new Date().toISOString(),
    })
  }

  async readCurrentDataMode(): Promise<{
    mode: KickoffDataMode
    source: 'marker' | 'inferred'
    suite_id?: string | null
    suite_label?: string | null
    baseline_id?: string | null
  } | null> {
    const payload = await safeReadJson<Record<string, unknown>>(DATA_MODE_PATH)
    if (!payload || typeof payload.mode !== 'string') {
      return null
    }
    return {
      mode: payload.mode as KickoffDataMode,
      source: 'marker',
      suite_id: typeof payload.suite_id === 'string' ? payload.suite_id : null,
      suite_label: typeof payload.suite_label === 'string' ? payload.suite_label : null,
      baseline_id: typeof payload.baseline_id === 'string' ? payload.baseline_id : null,
    }
  }

  buildArtifacts(runId: string): KickoffRunArtifacts & {
    context_pack_path: string
    generated_patch_path: string
    import_report_path: string
    readiness_snapshot_path: string
    diff_summary_path: string
    repair_patch_path: string
    failure_log_path: string
  } {
    return {
      context_pack_path: this.contextPackPath(runId),
      generated_patch_path: this.generatedPatchPath(runId),
      import_report_path: this.importReportPath(runId),
      readiness_snapshot_path: this.readinessPath(runId),
      diff_summary_path: this.diffSummaryPath(runId),
      repair_patch_path: this.repairPatchPath(runId),
      failure_log_path: this.failureLogPath(runId),
    }
  }

  private contextPackPath(runId: string): string {
    return resolve(RUNS_ROOT, runId, 'context-pack.json')
  }

  private generatedPatchPath(runId: string): string {
    return resolve(RUNS_ROOT, runId, 'generated-patch.yaml')
  }

  private importReportPath(runId: string): string {
    return resolve(RUNS_ROOT, runId, 'import-report.json')
  }

  private readinessPath(runId: string): string {
    return resolve(RUNS_ROOT, runId, 'readiness-snapshot.json')
  }

  private diffSummaryPath(runId: string): string {
    return resolve(RUNS_ROOT, runId, 'diff-summary.md')
  }

  private repairPatchPath(runId: string): string {
    return resolve(RUNS_ROOT, runId, 'repair-patch.yaml')
  }

  private failureLogPath(runId: string): string {
    return resolve(RUNS_ROOT, runId, 'failure-log.json')
  }

  private async writeJson(path: string, payload: unknown): Promise<void> {
    await mkdir(resolve(path, '..'), { recursive: true })
    await writeFile(path, JSON.stringify(payload, null, 2), 'utf8')
  }
}
