import { describe, expect, it } from 'vitest'
import type {
  DiscussionForestProjection,
  EffectiveParticipationContract,
  PostSemanticCapsule,
  ThreadCapsule,
} from '../../../shared/forum-orchestration.js'
import { AgentPerceptionService } from '../agent-perception-service.js'

const participationContract: EffectiveParticipationContract = {
  schema_version: 'forum-participation-contract.v2',
  scope_type: 'POST',
  scope_id: 'post-1',
  source: 'post_override',
  public_participation_mode: 'open_reply',
  audience_signal_ingestion: 'summary_only',
  agent_human_response_mode: 'aftershow_only',
  stage_open_reply: {
    schema_version: 'forum-participation-contract.v2',
    enabled: true,
    new_thread_enabled: true,
    turn_reply_enabled: true,
    public_participation_mode: 'open_reply',
    agent_human_response_mode: 'aftershow_only',
    explainability_scope: 'PUBLIC_SAFE_ONLY',
  },
  audience_lane: {
    schema_version: 'forum-participation-contract.v2',
    enabled: true,
    posting_enabled: false,
    audience_signal_ingestion: 'summary_only',
    agent_human_response_mode: 'aftershow_only',
    explainability_scope: 'PUBLIC_SAFE_ONLY',
  },
  community_default: null as never,
  post_override: null,
}

const postCapsule: PostSemanticCapsule = {
  schema_version: 'forum-post-semantic-capsule.v1',
  post_id: 'post-1',
  community_id: 'comm-1',
  thread_count: 1,
  highlighted_thread_ids: ['thread-1'],
  participant_ids: ['agent-a', 'agent-b'],
  participant_count: 2,
  latest_activity_at: new Date().toISOString(),
  audience_signals: null,
  thread_capsules: [],
  flow_phase: 'ESCALATION',
  premise: 'Premise',
  current_tension: 'Tension',
  resolved_points: [],
  open_questions: ['Question 1', 'Question 2'],
  must_read_turn_ids: ['turn-1'],
  start_thread_ids: ['thread-1'],
  thread_capsule_ids: ['thread-1'],
  audience_capsule_id: null,
  evidence_refs: [],
  public_persona_cues: [],
  public_growth_cues: [],
  updated_at: new Date().toISOString(),
}

const threadCapsule: ThreadCapsule = {
  schema_version: 'forum-thread-capsule.v1',
  thread_id: 'thread-1',
  post_id: 'post-1',
  community_id: 'comm-1',
  author_id: 'agent-a',
  participant_ids: ['agent-a', 'agent-b'],
  participant_count: 2,
  turn_count: 3,
  latest_turn_id: 'turn-2',
  latest_activity_at: new Date().toISOString(),
  lifecycle: {
    schema_version: 'forum-thread-lifecycle.v1',
    thread_id: 'thread-1',
    state: 'HEATING',
    thread_state: 'HEATING',
    reply_budget: {
      schema_version: 'forum-reply-budget.v1',
      thread_id: 'thread-1',
      limit: 6,
      used: 2,
      remaining: 4,
      exhausted: false,
      mode: 'SOFT_CAP',
      soft_cap_turns: 6,
      hard_cap_turns: null,
      remaining_turns: 4,
      cooldown_seconds: null,
      late_entry_reserved_slots: 1,
      revive_reserved_slots: 1,
      same_pair_cap: 2,
      last_evaluated_at: new Date().toISOString(),
    },
    active_route: null,
    writeability: {
      schema_version: 'forum-thread-writeability.v1',
      thread_id: 'thread-1',
      reply_mode: 'OPEN',
      reply_allowed: true,
      preferred_action: 'REPLY_IN_THREAD',
      reason_code: 'THREAD_OPEN',
    },
    lifecycle_label: 'ACTIVE',
    updated_at: new Date().toISOString(),
  },
  route_handoff: null,
  role: 'COUNTERPOINT',
  summary: 'Thread summary',
  unresolved_points: ['Question 1'],
  resolved_points: [],
  salient_turn_ids: ['turn-1', 'turn-2'],
  reason_badges: ['MENTIONED'],
  semantic_marks: [],
  audience_signals: null,
  guide_score: 1,
  evidence_refs: [],
  public_persona_cues: [],
  public_growth_cues: [],
  updated_at: new Date().toISOString(),
}

const forest: DiscussionForestProjection = {
  schema_version: 'forum-discussion-forest.v1',
  projection_id: 'forest-1',
  post_id: 'post-1',
  focus_thread_id: 'thread-1',
  focus_turn_id: 'turn-2',
  reading_guide: {
    schema_version: 'forum-reading-guide.v1',
    post_id: 'post-1',
    entries: [],
    highlighted_thread_ids: ['thread-1'],
    summary_line: 'summary',
    start_here_thread_ids: ['thread-1'],
    current_focus_thread_ids: ['thread-1'],
    must_read_turn_ids: ['turn-1'],
    evidence_refs: [],
    generated_at: new Date().toISOString(),
  },
  branch_groups: [],
  nodes: [
    {
      schema_version: 'forum-turn-display-projection.v1',
      id: 'thread-1',
      entry_kind: 'THREAD',
      post_id: 'post-1',
      thread_id: 'thread-1',
      display_parent_id: null,
      display_depth: 0,
      actual_anchor_turn_id: null,
      branch_root_turn_id: null,
      sibling_order: 0,
      collapsed_anchor_chain: [],
      is_late_entry: false,
      placement_reason: 'ROOT_APPEND',
      anchor_preview_source: 'NONE',
      reason_badges: [],
      author: { id: 'agent-a', actor_type: 'agent', display_name: 'Agent A', avatar_url: null },
      body: 'Thread root',
      quoted_excerpt: null,
      evidence_refs: [],
      created_at: new Date().toISOString(),
      generated_at: new Date().toISOString(),
    },
    {
      schema_version: 'forum-turn-display-projection.v1',
      id: 'turn-2',
      entry_kind: 'TURN',
      post_id: 'post-1',
      thread_id: 'thread-1',
      display_parent_id: 'thread-1',
      display_depth: 1,
      actual_anchor_turn_id: 'turn-1',
      branch_root_turn_id: 'thread-1',
      sibling_order: 1,
      collapsed_anchor_chain: [],
      is_late_entry: false,
      placement_reason: 'DIRECT_REPLY',
      anchor_preview_source: 'VISIBLE_TURN',
      reason_badges: ['MENTIONED'],
      author: { id: 'agent-b', actor_type: 'agent', display_name: 'Agent B', avatar_url: null },
      body: 'Reply',
      quoted_excerpt: null,
      evidence_refs: [],
      created_at: new Date().toISOString(),
      generated_at: new Date().toISOString(),
    },
  ],
  latest_activity_cursor: null,
  evidence_refs: [],
  generated_at: new Date().toISOString(),
}

describe('AgentPerceptionService', () => {
  it('builds an agent-aware slice with allowed actions and visible evidence ids', () => {
    const service = new AgentPerceptionService()

    const slice = service.buildSlice({
      agent_id: 'agent-z',
      post_capsule: postCapsule,
      thread_capsule: threadCapsule,
      forest,
      participation_contract: participationContract,
      focus_turn_id: 'turn-2',
    })

    expect(slice).toMatchObject({
      agent_id: 'agent-z',
      thread_id: 'thread-1',
      browse_reason: 'DIRECT_CHALLENGE',
      context_coverage: 'LOCAL_PLUS_POST',
      allowed_actions: expect.arrayContaining(['REPLY', 'HANDOFF', 'IGNORE']),
      visible_node_ids: expect.arrayContaining(['thread-1', 'turn-2']),
      evidence_window_ids: expect.arrayContaining(['turn-2']),
      thread_view: expect.objectContaining({
        summary: 'Thread summary',
        thread_state: 'HEATING',
      }),
    })
  })
})
