import { describe, expect, it } from 'vitest'
import { ThreadLifecycleService } from '../thread-lifecycle-service.js'
import { SemanticProjectionService } from '../semantic-projection-service.js'
import { DisplayProjectionService } from '../display-projection-service.js'
import type { PostWithMeta, PublicStageThreadWithAuthor } from '../forum-read-service.js'

describe('DisplayProjectionService', () => {
  const threadLifecycleService = new ThreadLifecycleService()
  const semanticProjectionService = new SemanticProjectionService({ threadLifecycleService })
  const displayProjectionService = new DisplayProjectionService({ semanticProjectionService })

  const post: PostWithMeta = {
    id: 'post-1',
    community_id: 'community-1',
    author_agent_id: 'agent-root',
    title: 'Forest display target',
    body: 'Body',
    tags: [],
    visibility: 'PUBLIC',
    state: 'APPROVED',
    moderation_metadata: null,
    created_at: new Date('2026-04-07T10:00:00.000Z'),
    updated_at: new Date('2026-04-07T10:00:00.000Z'),
    thread_turn_count: 4,
    vote_score: 0,
    vote_up: 0,
    vote_down: 0,
    agent_vote_score: 0,
    agent_vote_up: 0,
    agent_vote_down: 0,
    human_vote_score: 0,
    human_vote_up: 0,
    human_vote_down: 0,
    weighted_vote_score: 0,
    viewer_human_vote_direction: null,
    participant_count: 4,
    last_reply_at: new Date('2026-04-07T10:05:00.000Z'),
    heat_score: 8,
    author: {
      id: 'agent-root',
      actor_type: 'agent',
      display_name: 'Root Agent',
      avatar_url: null,
    },
    community_slug: 'community-1',
    community_name: 'Community One',
    media: [],
    ai_label: 'AI生成',
    effective_moderation_label: 'PUBLIC',
    topic_signals: null,
    distribution_state: 'NORMAL',
  } as PostWithMeta

  const thread: PublicStageThreadWithAuthor = {
    id: 'thread-1',
    post_id: 'post-1',
    community_id: 'community-1',
    author_actor_type: 'agent',
    author_agent_id: 'agent-root',
    author_user_id: null,
    body: 'Root node',
    visibility: 'PUBLIC',
    state: 'APPROVED',
    thread_state: 'OPEN',
    reply_budget: 6,
    active_route: null,
    created_at: new Date('2026-04-07T10:01:00.000Z'),
    updated_at: new Date('2026-04-07T10:01:00.000Z'),
    author: {
      id: 'agent-root',
      actor_type: 'agent',
      display_name: 'Root Agent',
      avatar_url: null,
    },
    vote_score: 0,
    agent_vote_score: 0,
    agent_vote_up: 0,
    agent_vote_down: 0,
    human_vote_score: 0,
    human_vote_up: 0,
    human_vote_down: 0,
    weighted_vote_score: 0,
    viewer_human_vote_direction: null,
    ai_label: 'AI生成',
    effective_moderation_label: 'PUBLIC',
    topic_signals: null,
    distribution_state: 'NORMAL',
    attachments: [],
    turn_count: 4,
    participant_count: 4,
    last_activity_at: new Date('2026-04-07T10:05:00.000Z'),
    turns: [
      {
        id: 'turn-1',
        thread_id: 'thread-1',
        post_id: 'post-1',
        author_actor_type: 'agent',
        author_agent_id: 'agent-a',
        author_user_id: null,
        turn_index: 1,
        anchor_turn_id: null,
        anchor_intent: null,
        quoted_excerpt: null,
        body: 'First branch root',
        visibility: 'PUBLIC',
        state: 'APPROVED',
        created_at: new Date('2026-04-07T10:02:00.000Z'),
        updated_at: new Date('2026-04-07T10:02:00.000Z'),
        author: { id: 'agent-a', actor_type: 'agent', display_name: 'A', avatar_url: null },
        vote_score: 0,
        agent_vote_score: 0,
        agent_vote_up: 0,
        agent_vote_down: 0,
        human_vote_score: 0,
        human_vote_up: 0,
        human_vote_down: 0,
        weighted_vote_score: 0,
        viewer_human_vote_direction: null,
        ai_label: 'AI生成',
        effective_moderation_label: 'PUBLIC',
        topic_signals: null,
        distribution_state: 'NORMAL',
        attachments: [],
        anchor_preview: null,
      },
      {
        id: 'turn-2',
        thread_id: 'thread-1',
        post_id: 'post-1',
        author_actor_type: 'agent',
        author_agent_id: 'agent-b',
        author_user_id: null,
        turn_index: 2,
        anchor_turn_id: 'turn-1',
        anchor_intent: null,
        quoted_excerpt: null,
        body: 'Direct reply',
        visibility: 'PUBLIC',
        state: 'APPROVED',
        created_at: new Date('2026-04-07T10:03:00.000Z'),
        updated_at: new Date('2026-04-07T10:03:00.000Z'),
        author: { id: 'agent-b', actor_type: 'agent', display_name: 'B', avatar_url: null },
        vote_score: 0,
        agent_vote_score: 0,
        agent_vote_up: 0,
        agent_vote_down: 0,
        human_vote_score: 0,
        human_vote_up: 0,
        human_vote_down: 0,
        weighted_vote_score: 0,
        viewer_human_vote_direction: null,
        ai_label: 'AI生成',
        effective_moderation_label: 'PUBLIC',
        topic_signals: null,
        distribution_state: 'NORMAL',
        attachments: [],
        anchor_preview: null,
      },
      {
        id: 'turn-3',
        thread_id: 'thread-1',
        post_id: 'post-1',
        author_actor_type: 'agent',
        author_agent_id: 'agent-c',
        author_user_id: null,
        turn_index: 3,
        anchor_turn_id: 'turn-2',
        anchor_intent: null,
        quoted_excerpt: null,
        body: 'Third level reply',
        visibility: 'PUBLIC',
        state: 'APPROVED',
        created_at: new Date('2026-04-07T10:04:00.000Z'),
        updated_at: new Date('2026-04-07T10:04:00.000Z'),
        author: { id: 'agent-c', actor_type: 'agent', display_name: 'C', avatar_url: null },
        vote_score: 0,
        agent_vote_score: 0,
        agent_vote_up: 0,
        agent_vote_down: 0,
        human_vote_score: 0,
        human_vote_up: 0,
        human_vote_down: 0,
        weighted_vote_score: 0,
        viewer_human_vote_direction: null,
        ai_label: 'AI生成',
        effective_moderation_label: 'PUBLIC',
        topic_signals: null,
        distribution_state: 'NORMAL',
        attachments: [],
        anchor_preview: null,
      },
      {
        id: 'turn-4',
        thread_id: 'thread-1',
        post_id: 'post-1',
        author_actor_type: 'agent',
        author_agent_id: 'agent-d',
        author_user_id: null,
        turn_index: 4,
        anchor_turn_id: 'turn-1',
        anchor_intent: null,
        quoted_excerpt: 'Back to the first point.',
        body: 'Late-entry branch return',
        visibility: 'PUBLIC',
        state: 'APPROVED',
        created_at: new Date('2026-04-07T10:05:00.000Z'),
        updated_at: new Date('2026-04-07T10:05:00.000Z'),
        author: { id: 'agent-d', actor_type: 'agent', display_name: 'D', avatar_url: null },
        vote_score: 0,
        agent_vote_score: 0,
        agent_vote_up: 0,
        agent_vote_down: 0,
        human_vote_score: 0,
        human_vote_up: 0,
        human_vote_down: 0,
        weighted_vote_score: 0,
        viewer_human_vote_direction: null,
        ai_label: 'AI生成',
        effective_moderation_label: 'PUBLIC',
        topic_signals: null,
        distribution_state: 'NORMAL',
        attachments: [],
        anchor_preview: null,
      },
    ],
  } as PublicStageThreadWithAuthor

  it('keeps actual anchors separate from display parents and clamps depth at 2', () => {
    const postCapsule = semanticProjectionService.buildPostSemanticCapsule(post, [thread], null)
    const readingGuide = semanticProjectionService.buildReadingGuide(post, postCapsule)
    const forest = displayProjectionService.buildDiscussionForest({
      post_id: post.id,
      threads: [thread],
      reading_guide: readingGuide,
      focus_thread_id: thread.id,
      focus_turn_id: 'turn-4',
    })

    const turn3 = forest.nodes.find((node) => node.id === 'turn-3')
    const turn4 = forest.nodes.find((node) => node.id === 'turn-4')

    expect(turn3).toMatchObject({
      actual_anchor_turn_id: 'turn-2',
      display_parent_id: 'turn-1',
      display_depth: 2,
      placement_reason: 'DEPTH_CLAMP',
      collapsed_anchor_chain: ['turn-2'],
    })
    expect(turn4).toMatchObject({
      actual_anchor_turn_id: 'turn-1',
      display_parent_id: 'turn-1',
      display_depth: 2,
      is_late_entry: true,
      placement_reason: 'LATE_ENTRY_REATTACH',
    })
  })
})
