import type { PromptScene } from '../runtime/types.js'
import type {
  LLMGenerationIntent,
  LLMVisibility,
  PromptTemplateRef,
} from './gateway-contract.js'
import type {
  RenderTier,
  VoiceLineId,
  VoiceLineRoutingIntent,
} from '../../shared/agent-persona-catalog.js'

export interface LlmCallsiteInventoryEntry {
  source_id: string
  source_file: string
  scene: PromptScene | 'background_hidden' | 'dev_prompt_render'
  dispatch_calls: Array<
    'llmGateway.generateVisibleText' |
    'llmGateway.generateHiddenArtifact' |
    'llmGateway.generateIdentityWrite' |
    'promptEngine.render'
  >
  evidence_patterns: string[]
  intent: LLMGenerationIntent
  visibility: LLMVisibility
  prompt_ref: PromptTemplateRef
  voice_line_authority: string
  tier_floor: RenderTier | 'identityWriteTier' | 'n/a'
  expected_profile_refs: Partial<Record<VoiceLineId, string>> | null
  raw_model_notes: string | null
  target_gateway_surface: string
  target_policy_id: string | null
  policy_binding_mode: 'profile-default' | 'callsite-execution-policy' | 'not-applicable'
  migration_status: 'migrated' | 'dual-track' | 'intentionally-retained'
  local_override_fields: Array<
    'timeoutMs' |
    'maxRetries' |
    'regionHint'
  >
  local_override_notes: string | null
  migration_blocker: string
}

export const LLM_DIRECT_CALL_GUARD_COUNTS: Record<
  string,
  Partial<Record<'llmClient.chat' | 'promptEngine.render', number>>
> = {
  'src/backend/llm/llm-gateway.ts': {
    'llmClient.chat': 1,
    'promptEngine.render': 1,
  },
  'src/backend/app.ts': {
    'promptEngine.render': 1,
  },
  'src/backend/media/media-semantic-service.ts': {
    'promptEngine.render': 1,
  },
}

export const LLM_CALLSITE_INVENTORY: LlmCallsiteInventoryEntry[] = [
  {
    source_id: 'agent-executor-forum-post',
    source_file: 'src/backend/runtime/agent-executor.ts',
    scene: 'forum_post',
    dispatch_calls: ['llmGateway.generateVisibleText'],
    evidence_patterns: [
      "case 'NewPostCreated'",
      'PROMPT_TEMPLATE_REFS.agentReplyToPost',
      'this.deps.llmGateway.generateVisibleText({',
      'scene: promptScene',
    ],
    intent: 'forum_reply',
    visibility: 'visible',
    prompt_ref: { id: 'agent-reply-to-post', version: 4 },
    voice_line_authority: 'Forum post replies must resolve from the agent home voice line instead of bootstrap config.llm defaults.',
    tier_floor: 'base',
    expected_profile_refs: {
      'qwen-social-v1': 'qwen-social-forum-reply-base',
      'glm-deep-v1': 'glm-deep-forum-reply-base',
    },
    raw_model_notes: 'Raw inline overrides remain removed; forum post replies now route only through registry-owned profile authority.',
    target_gateway_surface: 'LLMGateway.generateVisibleText',
    target_policy_id: 'visible-forum_reply-base',
    policy_binding_mode: 'profile-default',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Migrated to gateway envelope; keep this inventory entry to prevent regressions.',
  },
  {
    source_id: 'agent-executor-forum-thread-arrival-selection',
    source_file: 'src/backend/runtime/agent-executor.ts',
    scene: 'forum_thread',
    dispatch_calls: ['llmGateway.generateVisibleText'],
    evidence_patterns: [
      'PROMPT_TEMPLATE_REFS.agentSelectForumArrival',
      'responseMode: \'json_object\'',
      'this.deps.llmGateway.generateVisibleText({',
      'requestedTier: decisionRouting.requestedTier',
    ],
    intent: 'forum_reply',
    visibility: 'visible',
    prompt_ref: { id: 'agent-select-forum-arrival', version: 2 },
    voice_line_authority: 'Forum roaming arrival selection stays on forum_reply routing authority, but requests the lite tier and json-object mode for structured choice.',
    tier_floor: 'lite',
    expected_profile_refs: {
      'qwen-social-v1': 'qwen-social-forum-reply-lite',
      'glm-deep-v1': 'glm-deep-forum-reply-base',
    },
    raw_model_notes: 'The selection call stays on forum_reply voice-line authority, but it binds a dedicated json-object execution policy so the base body-generation policy is not reused accidentally.',
    target_gateway_surface: 'LLMGateway.generateVisibleText',
    target_policy_id: 'visible-forum_reply-selection-lite',
    policy_binding_mode: 'callsite-execution-policy',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Keep this entry to guard the dedicated arrival-selection callsite and prevent it from drifting back into the body-generation path.',
  },
  {
    source_id: 'agent-executor-forum-thread',
    source_file: 'src/backend/runtime/agent-executor.ts',
    scene: 'forum_thread',
    dispatch_calls: ['llmGateway.generateVisibleText'],
    evidence_patterns: [
      "case 'ThreadOpened'",
      'PROMPT_TEMPLATE_REFS.agentReplyToThreadTurn',
      'this.deps.llmGateway.generateVisibleText({',
      'scene: promptScene',
    ],
    intent: 'forum_reply',
    visibility: 'visible',
    prompt_ref: { id: 'agent-reply-to-thread-turn', version: 4 },
    voice_line_authority: 'Thread turns still resolve through forum_reply intent, but now on top of homeVoiceLineId authority.',
    tier_floor: 'base',
    expected_profile_refs: {
      'qwen-social-v1': 'qwen-social-forum-reply-base',
      'glm-deep-v1': 'glm-deep-forum-reply-base',
    },
    raw_model_notes: 'Raw inline overrides remain removed; thread replies now route only through registry-owned profile authority.',
    target_gateway_surface: 'LLMGateway.generateVisibleText',
    target_policy_id: 'visible-forum_reply-base',
    policy_binding_mode: 'profile-default',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Migrated to gateway envelope; keep this inventory entry to prevent regressions.',
  },
  {
    source_id: 'conversation-clock-chat-reply',
    source_file: 'src/backend/services/conversation-clock/message-generator.ts',
    scene: 'chat_room',
    dispatch_calls: ['llmGateway.generateVisibleText'],
    evidence_patterns: [
      'PROMPT_TEMPLATE_REFS.agentChatReply',
      'context.deps.llmGateway.generateVisibleText({',
      "intent: 'chat_reply'",
    ],
    intent: 'chat_reply',
    visibility: 'visible',
    prompt_ref: { id: 'agent-chat-reply', version: 6 },
    voice_line_authority: 'Chat room replies must resolve from homeVoiceLineId and chat_room policy, not bootstrap config.llm.',
    tier_floor: 'lite',
    expected_profile_refs: {
      'qwen-social-v1': 'qwen-social-chat-reply-lite',
      'glm-deep-v1': 'glm-deep-chat-reply-lite',
    },
    raw_model_notes: 'Removed; chat room replies now route through the gateway.',
    target_gateway_surface: 'LLMGateway.generateVisibleText',
    target_policy_id: 'visible-chat_reply-lite',
    policy_binding_mode: 'profile-default',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Migrated to gateway envelope; keep this inventory entry to prevent regressions.',
  },
  {
    source_id: 'post-scheduler-create-post',
    source_file: 'src/backend/runtime/post-scheduler.ts',
    scene: 'scheduled_post',
    dispatch_calls: ['llmGateway.generateVisibleText'],
    evidence_patterns: [
      'PROMPT_TEMPLATE_REFS.agentCreatePostScene',
      'this.deps.llmGateway.generateVisibleText({',
      "intent: 'scheduled_post'",
    ],
    intent: 'scheduled_post',
    visibility: 'visible',
    prompt_ref: { id: 'agent-create-post', version: 4 },
    voice_line_authority: 'Scheduled posting now resolves from homeVoiceLineId plus scheduled_post tier policy.',
    tier_floor: 'base',
    expected_profile_refs: {
      'qwen-social-v1': 'qwen-social-scheduled-post-base',
      'glm-deep-v1': 'glm-deep-scheduled-post-base',
    },
    raw_model_notes: 'Raw inline overrides remain removed; scheduled posts now route only through registry-owned profile authority.',
    target_gateway_surface: 'LLMGateway.generateVisibleText',
    target_policy_id: 'visible-scheduled_post-base',
    policy_binding_mode: 'profile-default',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Migrated to gateway envelope; keep this inventory entry to prevent regressions.',
  },
  {
    source_id: 'private-channel-reply',
    source_file: 'src/backend/services/private-channel-service.ts',
    scene: 'private_chat',
    dispatch_calls: ['llmGateway.generateVisibleText'],
    evidence_patterns: [
      'this.deps.llmGateway.generateVisibleText({',
      "intent: 'private_reply'",
    ],
    intent: 'private_reply',
    visibility: 'visible',
    prompt_ref: { id: 'agent-private-chat-reply', version: 3 },
    voice_line_authority: 'Private replies derive from homeVoiceLineId and registry routing only; no compatibility model hint remains in candidate selection.',
    tier_floor: 'base',
    expected_profile_refs: {
      'qwen-social-v1': 'qwen-social-private-reply-base',
      'glm-deep-v1': 'glm-deep-private-reply-base',
    },
    raw_model_notes: 'Private reply now binds directly to the registry-owned realtime execution policy through the profile contract.',
    target_gateway_surface: 'LLMGateway.generateVisibleText',
    target_policy_id: 'visible-private_reply-realtime',
    policy_binding_mode: 'profile-default',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Migrated to a profile-owned realtime policy; keep this inventory entry to prevent callsite policy drift or raw parameter regressions.',
  },
  {
    source_id: 'proactive-orchestrated-opening',
    source_file: 'src/backend/services/proactive-interaction-service.ts',
    scene: 'proactive_dm',
    dispatch_calls: ['llmGateway.generateVisibleText'],
    evidence_patterns: [
      'PROMPT_TEMPLATE_REFS.agentProactiveDmOpening',
      'this.deps.llmGateway.generateVisibleText({',
      "intent: 'proactive_opening'",
    ],
    intent: 'proactive_opening',
    visibility: 'visible',
    prompt_ref: { id: 'agent-proactive-dm-opening', version: 3 },
    voice_line_authority: 'Proactive openings resolve from homeVoiceLineId and proactive_dm policy with orchestrated private-boundary inputs.',
    tier_floor: 'base',
    expected_profile_refs: {
      'qwen-social-v1': 'qwen-social-proactive-opening-base',
      'glm-deep-v1': 'glm-deep-proactive-opening-base',
    },
    raw_model_notes: 'Proactive opening now inherits its policy defaults from the visible proactive execution policy instead of callsite tuning.',
    target_gateway_surface: 'LLMGateway.generateVisibleText',
    target_policy_id: 'visible-proactive_opening-base',
    policy_binding_mode: 'profile-default',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Migrated to registry-owned proactive-opening defaults; keep this entry to guard against raw parameter reintroduction.',
  },
  {
    source_id: 'public-observation-digest',
    source_file: 'src/backend/services/public-observation-digest-service.ts',
    scene: 'background_hidden',
    dispatch_calls: ['llmGateway.generateHiddenArtifact'],
    evidence_patterns: [
      'PROMPT_TEMPLATE_REFS.internalPublicObservationDigest',
      'this.deps.llmGateway.generateHiddenArtifact({',
      "intent: 'public_observation_digest'",
    ],
    intent: 'public_observation_digest',
    visibility: 'hidden',
    prompt_ref: { id: 'internal-public-observation-digest', version: 1 },
    voice_line_authority: 'Public observation digest must stay on the hidden director line and remain detached from visible home voice authority.',
    tier_floor: 'base',
    expected_profile_refs: {
      'deepseek-director-v1': 'deepseek-director-public-observation-base',
    },
    raw_model_notes: 'Public observation digest now stays on the public-facing hidden policy path without any callsite temperature override.',
    target_gateway_surface: 'LLMGateway.generateHiddenArtifact',
    target_policy_id: 'hidden-public_observation_digest-base',
    policy_binding_mode: 'profile-default',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Migrated to the public-facing hidden digest policy; keep this entry to guard the public lane contract.',
  },
  {
    source_id: 'agent-social-bio-render',
    source_file: 'src/backend/services/agent-bio-render-service.ts',
    scene: 'background_hidden',
    dispatch_calls: ['llmGateway.generateHiddenArtifact'],
    evidence_patterns: [
      'PROMPT_TEMPLATE_REFS.internalAgentSocialBioRender',
      'this.deps.llmGateway.generateHiddenArtifact({',
      "intent: 'public_observation_digest'",
    ],
    intent: 'public_observation_digest',
    visibility: 'hidden',
    prompt_ref: { id: 'internal-agent-social-bio-render', version: 1 },
    voice_line_authority: 'Social bio projection now renders on the agent home voice line hidden digest lane so rhetoric families stay aligned with the agent voice instead of a global director line.',
    tier_floor: 'base',
    expected_profile_refs: {
      'qwen-social-v1': 'qwen-social-public-observation-base',
      'glm-deep-v1': 'glm-deep-public-observation-base',
      'minimax-her-v1': 'minimax-her-public-observation-base',
      'kimi-deep-v1': 'kimi-deep-public-observation-base',
    },
    raw_model_notes: 'Bio render now binds to a dedicated agent-bio execution policy instead of borrowing the public-facing digest defaults.',
    target_gateway_surface: 'LLMGateway.generateHiddenArtifact',
    target_policy_id: 'hidden-public_observation_digest-agent-bio-base',
    policy_binding_mode: 'callsite-execution-policy',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Migrated to an explicit agent-bio policy binding so bio generation no longer shares public hidden defaults or raw callsite params.',
  },
  {
    source_id: 'public-context-summary-extract',
    source_file: 'src/backend/context-memory/runtime.ts',
    scene: 'background_hidden',
    dispatch_calls: ['llmGateway.generateHiddenArtifact'],
    evidence_patterns: [
      'PROMPT_TEMPLATE_REFS.internalPublicObservationSummaryExtract',
      'this.deps.llmGateway.generateHiddenArtifact({',
      "traceId: `context-extract:${event.id}`",
    ],
    intent: 'public_observation_digest',
    visibility: 'hidden',
    prompt_ref: { id: 'internal-public-observation-summary-extract', version: 1 },
    voice_line_authority: 'Public context extraction stays on the hidden director line and reuses the public_observation_digest routing family.',
    tier_floor: 'base',
    expected_profile_refs: {
      'deepseek-director-v1': 'deepseek-director-public-observation-base',
    },
    raw_model_notes: 'Public context extract stays on the hidden public_observation_digest profile default policy; no callsite execution-policy override is allowed here.',
    target_gateway_surface: 'LLMGateway.generateHiddenArtifact',
    target_policy_id: 'hidden-public_observation_digest-base',
    policy_binding_mode: 'profile-default',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Public context extraction must stay on the profile-default hidden public observation policy, otherwise live runtime typed-ingest can fail closed on disallowed execution-policy overrides.',
  },
  {
    source_id: 'public-context-summary-distill',
    source_file: 'src/backend/context-memory/runtime.ts',
    scene: 'background_hidden',
    dispatch_calls: ['llmGateway.generateHiddenArtifact'],
    evidence_patterns: [
      'PROMPT_TEMPLATE_REFS.internalPublicObservationSummaryDistill',
      'this.deps.llmGateway.generateHiddenArtifact({',
      "traceId: `context-distill:${event.id}`",
    ],
    intent: 'public_observation_digest',
    visibility: 'hidden',
    prompt_ref: { id: 'internal-public-observation-summary-distill', version: 1 },
    voice_line_authority: 'Public context distill also stays on the hidden director line and must not route through visible home voice.',
    tier_floor: 'base',
    expected_profile_refs: {
      'deepseek-director-v1': 'deepseek-director-public-observation-base',
    },
    raw_model_notes: 'Public context distill also stays on the hidden public_observation_digest profile default policy without a callsite execution-policy override.',
    target_gateway_surface: 'LLMGateway.generateHiddenArtifact',
    target_policy_id: 'hidden-public_observation_digest-base',
    policy_binding_mode: 'profile-default',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Public context distill must keep the profile-default hidden public observation policy so live typed-ingest stays compatible with the registry contract.',
  },
  {
    source_id: 'public-context-identity-finalize',
    source_file: 'src/backend/context-memory/runtime.ts',
    scene: 'background_hidden',
    dispatch_calls: ['llmGateway.generateIdentityWrite'],
    evidence_patterns: [
      'PROMPT_TEMPLATE_REFS.internalPublicObservationIdentityFinalize',
      'this.deps.llmGateway.generateIdentityWrite({',
      "traceId: `identity-finalize:${agentId}:",
    ],
    intent: 'identity_write',
    visibility: 'identity_write',
    prompt_ref: { id: 'internal-public-observation-identity-finalize', version: 1 },
    voice_line_authority: 'Public observation finalize must resolve from the agent home voice line through the identity-write lane, but can request a lower identity tier than private digest.',
    tier_floor: 'base',
    expected_profile_refs: {
      'qwen-social-v1': 'qwen-social-identity-write-base',
      'glm-deep-v1': 'glm-deep-identity-write-premium',
    },
    raw_model_notes: 'Public identity finalize now relies on the strict identity-write base policy instead of callsite tuning.',
    target_gateway_surface: 'LLMGateway.generateIdentityWrite',
    target_policy_id: 'identity_write-identity_write-base',
    policy_binding_mode: 'profile-default',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Migrated to strict identity-write defaults; keep this entry to prevent raw writeback tuning from returning to callsites.',
  },
  {
    source_id: 'private-context-summary-extract',
    source_file: 'src/backend/context-memory/runtime.ts',
    scene: 'background_hidden',
    dispatch_calls: ['llmGateway.generateHiddenArtifact'],
    evidence_patterns: [
      'PROMPT_TEMPLATE_REFS.internalPrivateChatSummaryExtract',
      'this.deps.llmGateway.generateHiddenArtifact({',
      "traceId: `context-extract:${event.id}`",
    ],
    intent: 'private_digest',
    visibility: 'hidden',
    prompt_ref: { id: 'internal-private-chat-summary-extract', version: 1 },
    voice_line_authority: 'Private context extraction stays on the hidden director line and reuses the private_digest routing family.',
    tier_floor: 'base',
    expected_profile_refs: {
      'deepseek-director-v1': 'deepseek-director-private-digest-base',
    },
    raw_model_notes: 'Private extract now relies on the agent-owned private-digest policy defaults from registry.',
    target_gateway_surface: 'LLMGateway.generateHiddenArtifact',
    target_policy_id: 'hidden-private_digest-base',
    policy_binding_mode: 'profile-default',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Migrated to registry-owned private-digest defaults; keep this entry to prevent raw hidden extract tuning from returning.',
  },
  {
    source_id: 'private-context-summary-distill',
    source_file: 'src/backend/context-memory/runtime.ts',
    scene: 'background_hidden',
    dispatch_calls: ['llmGateway.generateHiddenArtifact'],
    evidence_patterns: [
      'PROMPT_TEMPLATE_REFS.internalPrivateChatSummaryDistill',
      'this.deps.llmGateway.generateHiddenArtifact({',
      "traceId: `context-distill:${event.id}`",
    ],
    intent: 'private_digest',
    visibility: 'hidden',
    prompt_ref: { id: 'internal-private-chat-summary-distill', version: 1 },
    voice_line_authority: 'Private context distill also stays on the hidden director line and must not route through visible home voice.',
    tier_floor: 'base',
    expected_profile_refs: {
      'deepseek-director-v1': 'deepseek-director-private-digest-base',
    },
    raw_model_notes: 'Private distill now relies on the agent-owned private-digest policy defaults from registry.',
    target_gateway_surface: 'LLMGateway.generateHiddenArtifact',
    target_policy_id: 'hidden-private_digest-base',
    policy_binding_mode: 'profile-default',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Migrated to registry-owned private-digest defaults; keep this entry to prevent raw hidden distill tuning from returning.',
  },
  {
    source_id: 'private-context-identity-finalize',
    source_file: 'src/backend/context-memory/runtime.ts',
    scene: 'background_hidden',
    dispatch_calls: ['llmGateway.generateIdentityWrite'],
    evidence_patterns: [
      'PROMPT_TEMPLATE_REFS.internalPrivateChatIdentityFinalize',
      'this.deps.llmGateway.generateIdentityWrite({',
      "traceId: `identity-finalize:${agentId}:",
    ],
    intent: 'identity_write',
    visibility: 'identity_write',
    prompt_ref: { id: 'internal-private-chat-identity-finalize', version: 1 },
    voice_line_authority: 'Private identity finalize must resolve from the agent home voice line through the identity-write lane and can request the higher private tier.',
    tier_floor: 'identityWriteTier',
    expected_profile_refs: {
      'qwen-social-v1': 'qwen-social-identity-write-premium',
      'glm-deep-v1': 'glm-deep-identity-write-premium',
    },
    raw_model_notes: 'Private identity finalize now relies on the strict identity-write premium policy instead of callsite tuning.',
    target_gateway_surface: 'LLMGateway.generateIdentityWrite',
    target_policy_id: 'identity_write-identity_write-premium',
    policy_binding_mode: 'profile-default',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Migrated to strict identity-write premium defaults; keep this entry to prevent raw writeback tuning from returning.',
  },
  {
    source_id: 'vision-summary',
    source_file: 'src/backend/media/media-semantic-service.ts',
    scene: 'background_hidden',
    dispatch_calls: ['llmGateway.generateHiddenArtifact'],
    evidence_patterns: [
      'PROMPT_TEMPLATE_REFS.internalVisionSummary',
      'type: \'image_url\'',
      'agentId: input.agentId ?? \'media-semantic\'',
      'this.deps.llmGateway.generateHiddenArtifact({',
    ],
    intent: 'vision_summary',
    visibility: 'hidden',
    prompt_ref: { id: 'internal-vision-summary', version: 1 },
    voice_line_authority: 'Multimodal hidden summaries stay on the hidden director line and remain detached from visible home voice authority.',
    tier_floor: 'base',
    expected_profile_refs: {
      'deepseek-director-v1': 'deepseek-director-vision-summary-base',
    },
    raw_model_notes: 'Vision summary now relies on the modality-specific hidden vision policy instead of callsite tuning.',
    target_gateway_surface: 'LLMGateway.generateHiddenArtifact',
    target_policy_id: 'hidden-vision_summary-base',
    policy_binding_mode: 'profile-default',
    migration_status: 'migrated',
    local_override_fields: [],
    local_override_notes: null,
    migration_blocker: 'Migrated to modality-specific vision defaults; keep this entry to prevent raw multimodal tuning from returning.',
  },
  {
    source_id: 'dev-prompt-render',
    source_file: 'src/backend/app.ts',
    scene: 'dev_prompt_render',
    dispatch_calls: ['promptEngine.render'],
    evidence_patterns: [
      'resolveCurrentVisiblePromptRef(body.template_id)',
      'promptEngine.render(promptRef, variables)',
    ],
    intent: 'dev_prompt_render',
    visibility: 'dev_only',
    prompt_ref: { id: 'dev-selected-template', version: 1 },
    voice_line_authority: 'Dev-only render inspects prompt contracts and never chooses provider/model routing.',
    tier_floor: 'n/a',
    expected_profile_refs: null,
    raw_model_notes: null,
    target_gateway_surface: 'PromptEngine.renderPromptRef',
    target_policy_id: null,
    policy_binding_mode: 'not-applicable',
    migration_status: 'intentionally-retained',
    local_override_fields: [],
    local_override_notes: 'Dev-only prompt rendering intentionally bypasses runtime routing and remains a prompt contract inspection surface.',
    migration_blocker: 'Dev route intentionally renders selected templates directly for contract inspection.',
  },
]

export function isRoutingIntent(intent: LLMGenerationIntent): intent is VoiceLineRoutingIntent {
  return intent !== 'dev_prompt_render'
}
